// Create a public share link for a backtest run.
//
// Caller must own the run. Short code is generated by the database default
// (`sys_short_id(10)` in 0001_init.sql).

import { NextResponse, type NextRequest } from "next/server";

import { requireUser } from "@/lib/supabase/auth";
import { db } from "@/lib/supabase/server";
import type { BtShareLinkInsert } from "@/lib/supabase/types";

export const dynamic = "force-dynamic";

type Body = { run_id?: string; expires_at?: string | null };

export async function POST(req: NextRequest) {
  const auth = await requireUser(req);
  if (!auth.user) return auth.res;
  const userAddress = auth.user.address;

  let body: Body;
  try {
    body = (await req.json()) as Body;
  } catch {
    return NextResponse.json({ error: "invalid JSON body" }, { status: 400 });
  }

  if (!body.run_id || typeof body.run_id !== "string") {
    return NextResponse.json({ error: "run_id required" }, { status: 400 });
  }

  // Ownership check — only the run's owner can mint a share link.
  const { data: run, error: runErr } = await db
    .from("bt_runs")
    .select("id")
    .eq("user_address", userAddress)
    .eq("id", body.run_id)
    .maybeSingle();

  if (runErr) {
    return NextResponse.json({ error: runErr.message }, { status: 500 });
  }
  if (!run) {
    return NextResponse.json({ error: "run not found" }, { status: 404 });
  }

  let expires_at: string | null = null;
  if (body.expires_at !== undefined && body.expires_at !== null) {
    if (typeof body.expires_at !== "string") {
      return NextResponse.json(
        { error: "expires_at must be ISO string or null" },
        { status: 400 },
      );
    }
    const parsed = Date.parse(body.expires_at);
    if (Number.isNaN(parsed)) {
      return NextResponse.json(
        { error: "expires_at must be a valid ISO timestamp" },
        { status: 400 },
      );
    }
    expires_at = new Date(parsed).toISOString();
  }

  const insert: BtShareLinkInsert = {
    run_id: body.run_id,
    created_by: userAddress,
    expires_at,
  };

  // Proxy-induced `never` narrowing on the dynamic `.from()` chain — cast
  // the payload through `never` to keep the type-checker happy.
  const { data, error } = await db
    .from("bt_share_links")
    .insert(insert)
    .select("short_code")
    .single();

  if (error || !data) {
    return NextResponse.json(
      { error: error?.message ?? "insert failed" },
      { status: 500 },
    );
  }

  return NextResponse.json({ short_code: (data as { short_code: string }).short_code });
}
